---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Install Apache on Ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: Install Apache on OracleLinux
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "OracleLinux"

